### ISSUE TITLE
Installation on Debian GNU/Linux 9 (stretch)

### ISSUE THREAD

**Issue by captain-yoshi** [MrPrimate/ddb-adventure-muncher#14]
Trying to run the adventure muncher from this package [ddb-adventure-muncher-0.7.4-linux-amd64.deb](ddb-adventure-muncher-0.7.4-linux-amd64.deb).

Missing library:
``` bash
$ ddb-adventure-muncher

ddb-adventure-muncher: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

# downloading the missing library
sudo apt install sudo apt-get install libasound2
```

Breakpoint:
``` bash
$ ddb-adventure-muncher

Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Trace/breakpoint trap
```

Bummer ! This Debian VM is a headless server, so I have to ssh with the `-X` option. All is fine after that. Just reporting in case somebody does the same steps.

**Comment by MrPrimate** [comment]
Yes, the adventure muncher requires gui components.
