### ISSUE TITLE
Stuck on Checking config...

### ISSUE THREAD

**Issue by DaviDeil** [MrPrimate/ddb-adventure-muncher#16]
DDB Adventure Muncher Windows x64 Version 1.0.0 (using Windows 10)

Using DDB Importer version 3.1.0

Stuck on 'Checking config...' after choosing to load adventure-config.json created by DDB Importer version 3.1.0. In the json it shows the correct cobalt code.

**Comment by herrozerro** [comment]
Same here

**Comment by DaviDeil** [comment]
`[2022-09-09 19:21:48.914] [info]  Using initial config directory C:\Users\...\AppData\Roaming\ddb-adventure-muncher
[2022-09-09 19:21:48.915] [info]  Config Directory is now C:\Users\...\AppData\Roaming\ddb-adventure-muncher
[2022-09-09 19:21:48.916] [info]  Getting External Config file C:\Users\...\AppData\Roaming\ddb-adventure-muncher\adventure-config.json
[2022-09-09 19:21:48.917] [info]  JSON file saved to C:\Users\...\AppData\Roaming\ddb-adventure-muncher\config.json
[2022-09-09 19:21:54.009] [info]  C:\Users\...\AppData\Roaming\ddb-adventure-muncher\logs
`

main.log file with personal name replaced with ellipses.

**Comment by NullOrNaN** [comment]
Can confirm I'm having the same issue on Windows 11.

**Comment by DaviDeil** [comment]
> Can confirm I'm having the same issue on Windows 11.
> 
> Have tried running as admin (Right click -> Run As Admin) and running as the normal user.

I have also tried running as admin.

**Comment by MrOutsider** [comment]
> .

I have the same issue, Windows 11.

**Comment by MrOutsider** [comment]
> Can confirm I'm having the same issue on Windows 11.
> 
> Have tried running as admin (Right click -> Run As Admin) and running as the normal user.

Same.

**Comment by MrPrimate** [comment]
This should be resolved in https://github.com/MrPrimate/ddb-adventure-muncher/releases/tag/v1.0.1
