### ISSUE TITLE
1.0.5 Stuck on "Checking config..." Forever

### ISSUE THREAD

**Issue by tfinnegan937** [MrPrimate/ddb-adventure-muncher#17]
When loading a config generated from the Adventure Muncher within Foundry VTT, the ddb-adventure-muncher application gets stuck on "Checking Config..." Forever. This has been tested on both Ubuntu 20.04 64-bit and Windows 11 64-bit.

Relevent Ubuntu command line output with both super-user and non super-user attempts included as an attachment

[adventure_muncher_issue.txt](https://github.com/MrPrimate/ddb-adventure-muncher/files/9544116/adventure_muncher_issue.txt)

**Comment by tfinnegan937** [comment]
Also note: Reverting to version 1.01 side-stepped this issue.

**Comment by MrPrimate** [comment]
Fixed in v1.0.6
