### ISSUE TITLE
Out of memory error when importing Ghosts of Saltmarsh

### ISSUE THREAD

**Issue by JKFWEB** [MrPrimate/ddb-adventure-muncher#18]
![image](https://user-images.githubusercontent.com/73962543/192816890-758e071a-5ebc-4c0d-a0b9-13bb2a386597.png)

I watched progress of importer and it finished with Journals and was about 70% of way through Roll Tables when Google Chrome displayed the "Aw Snap: Out of Memory" error.

I had all applications closed except Chrome, have 16GB of ram, and Task Manager was showing only 75% of memory was being used.

I tried 4 times with same results.

I am running V10 of Foundry, with D&D 5e game system.  All updates have been run for foundry, game system, and modules.  Running 1.07 of DDB Adventure Muncher.

**Comment by MrPrimate** [comment]
Have you tried with other modules disabled during the import?

**Comment by JKFWEB** [comment]
That worked!  Used same amount of memory but completed super quick and with no errors this time.

Thanks for the suggestion, honestly did not think that would be the issue :)
