### ISSUE TITLE
Muncher can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kefnab** [MrPrimate/ddb-adventure-muncher#26]
<img width="391" alt="Screenshot 2023-06-10 at 10 48 44" src="https://github.com/MrPrimate/ddb-adventure-muncher/assets/21352789/affc6800-9040-472c-be77-8390b1cf33c4">

ddb-adventure-muncher-1.4.1-mac-x64.dmg was installed into applications folder, but would not open.

## System Specs ##
iMac Retina 4k, 21.5-inch, 2019
3.2 GHz 6-Core Intel Core i7
Radeon Pro 560X 4 GB
16 GB 2667 MHz DDR4
MacOS 13.4 (22F66)

**Comment by MrPrimate** [comment]
Work around: https://support.apple.com/en-gb/guide/mac-help/mchleab3a043/mac

**Comment by MrPrimate** [comment]
Should be resolved in latest version, now notarized.
