### ISSUE TITLE
Does not pull down tabbed adventures

### ISSUE THREAD

**Issue by DasAmigo** [MrPrimate/ddb-adventure-muncher#27]
I need to import "Turn of fortunes wheel"  https://www.dndbeyond.com/sources/paitm/tofw 
However when importing planescape it only imports the intro. https://www.dndbeyond.com/sources/paitm

**Comment by MrPrimate** [comment]
![Screenshot from 2023-11-07 18-26-58](https://github.com/MrPrimate/ddb-adventure-muncher/assets/3985378/ab6e5bef-7472-4f24-ad8d-6a1fc61eb7a9)
They import for me.

Try clearing your downloaded info in Adventure Muncher and try again.
