### ISSUE TITLE
filter user available content by source book

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-adventure-muncher#3]
https://github.com/MrPrimate/ddb-adventure-muncher/blob/7740c2c6dc9fb7fb959965ea82cf4f1b10baf286/munch/ddb.js#L79-L81

As discussed on Discord, that ID that you filter out is for purchased dice sets, the other entity ids are for purchases races, classes, backgrounds, etc... so those ids will also all lead to false positive. If you want to filter only on books, then use EntityID `496802664`

**Comment by MrPrimate** [comment]
Fixed in next release/
